/** @format */
/**
 * todo redux type
 */
const Todo = {
  FETCH_TODO_SUCCESS: "FETCH_TODO_SUCCESS",
  FECTH_TODO_FAILURE: "FECTH_TODO_FAILURE",
  CREATE_TODO_SUCCUSS: "CREATE_TODO_SUCCUSS",
  CREATE_TODO_FIALURE: "CREATE_TODO_FIALURE",
  UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
};

const User = {
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_FAILURE: "LOGIN_REQUEST_FAILURE",
  LOGOUT_REQUEST_SUCCESS: "LOGOUT_REQUEST_SUCCESS",
  LOGOUT_REQUEST_FIALURE: "LOGOUT_REQUEST_FIALURE",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FIALURE: "CREATE_USER_FIALURE",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};

export const type = {
  User,
  Todo,
};
